// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Address struct {
	ID      string `json:"id"`
	Address string `json:"Address"`
}

type NewUser struct {
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
}

type UpdateUser struct {
	OldFirstname string `json:"oldFirstname"`
	NewFirstname string `json:"newFirstname"`
	NewLastname  string `json:"newLastname"`
}

type User struct {
	ID        string `json:"id"`
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
}

type Fname struct {
	OldFirstname string `json:"oldFirstname"`
	FirstName    string `json:"firstName"`
}
