// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewStudent struct {
	Name string `json:"name"`
}

type Student struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}

type UpdateStudent struct {
	ID      int    `json:"id"`
	NewName string `json:"newName"`
}
